using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetDeptQuery_LY.Entity.RegisterConfirmInfo.HIS
{
    public class YBOutMsg
    {
        public string SBKH = "";
        public string GMSFHM = "";
        public string XM = "";
        public string XB = "";
        public string MZ = "";
        public string CSD = "";
        public string CSRQ = "";
        public string WHCD = "";
        public string GRBH = "";
        public string XZZWJB = "";
        public string GWYBS = "";
        public string YDRYBS = "";
        public string BGRQ = "";
        public string SSQBH = "";
        public string YL2 = "";
        public string YLRYLB = "";
        public string DWBH = "";
        public string XZZT = "";
        public string JBXXYL1 = "";
        public string JBXXYL2 = "";
        public string BNZHYE = "";
        public string SCCYYYBM = "";
        public string SCCYYDJ = "";
        public string SCCYRQ = "";
        public string SCCYJBBM = "";
        public string SCQFX = "";
        public string SCQFXSJZF = "";
        public string SCCYYLLB = "";
        public string SCCYYY = "";
        public string SCFHJBYLFY = "";
        public string SCJRTCFY = "";
        public string ZHND = "";
        public string ZYZT = "";
        public string BNZFYLJ = "";
        public string BNZLFYLJ = "";
        public string BNZFFYLJ_1 = "";
        public string BNZFFYLJ_2 = "";
        public string BNJRTCFYLJ = "";
        public string BNJRJZJFYLJ = "";
        public string BNXJZCLJ = "";
        public string BNZHZCLJ = "";
        public string BNTCZCLJ = "";
        public string BNDBJZZCLJ = "";
        public string BNGWYBZZCLJ = "";
        public string BNBCBXZCLJ = "";
        public string BNZYCS = "";
        public string BNTSMZTCZCLJ = "";
        public string BNTSMZDEJZZCLJ = "";
        public string BNMZMXBTCZCLJ = "";
        public string BNMZMXBDBZCLJ = "";
        public string BNMZMXBFHJBYLFYLJ = "";
        public string BNMZMXBFHJBYLFYLJ_1 = "";
        public string BNMZMXBQFBZZFLJ = "";
        public string BNMZMXBYLYPZFLJ = "";
        public string BNMZMXBTJTZZFLJ = "";
        public string BNZYFHJBYLFYLJ_1 = "";
        public string BNZYFHJBYLFYLJ_2 = "";
        public string BNZYYLYPZFLJ = "";
        public string BNZYTJTZZFLJ = "";
        public string MZMXB1BM = "";
        public string MZMXB1TCZCLJ = "";
        public string MZMXB1DBJZZCLJ = "";
        public string MZMXB2BM = "";
        public string MZMXB2TCZCLJ = "";
        public string MZMXB2DBJZZCLJ = "";
        public string MZMXB3BM = "";
        public string MZMXB3TCZCLJ = "";
        public string MZMXB3DBJZZCLJ = "";
        public string MZMXB4BM = "";
        public string MZMXB4TCZCLJ = "";
        public string MZMXB4DBJZZCLJ = "";
        public string MZMXB5BM = "";
        public string MZMXB5TCZCLJ = "";
        public string MZMXB5DBJZZCLJ = "";
        public string ZHXXYL1 = "";
        public string ZHXXYL2 = "";
        public string BNTCBFJRBCYLLJ = "";
        public string BNDEBFJRBCYLLJ = "";
        public string BNTCBCYLBXZCLJ = "";
        public string BNDEBCYLBXZCLJ = "";
        public string BNBCYLBXZCLJ = "";
        public string GRSF = "";
        public string YDRYBZ = "";
        public string YLFZE = "";
        public string BCZHZF = "";
        public string TCZFJE = "";
        public string DBJZJJZF = "";
        public string GWYBZZF = "";
        public string QYBCJJZF = "";
        public string BCXJZF = "";
        public string ZFFY = "";
        public string YPZLFY = "";
        public string XMZLFY = "";
        public string TJTZZL = "";
        public string CCZLFAZFFY = "";
        public string QFBZZF = "";
        public string JRTCFY = "";
        public string TCFDZF = "";
        public string JRJZJFY = "";
        public string JZJZF = "";
        public string CFDXZF = "";
        public string FHJBYLFY = "";
        public string YBQFBZE = "";
        public string ZYCS = "";
        public string SCTCJZLJ = "";
        public string SCDELJ = "";
        public string TJGBGWYBZ = "";
        public string NZGPOXM = "";
        public string TCQH = "";
        public string MMYDEYE = "";


        public string Birthday = "";
        public string PatientID = "";
        public string PatientName = "";
        public string PatientSex = "";
        public string DJH = "";
        public string LSH = "";
        public string YLLB = "";
        public string GHRQ = "";
        public string KSMC = "";
        public string JBR = "";
        public string YWZQH = "";
        public string YYJYLSH = "";
        public string YBCardOutStr = "";
        public string YBCostOutStr = "";
    }
}